apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weddingbook-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: url_to_be_added_into_dns_records.com
spec:
  rules:
  - host: url_to_be_added_into_dns_records.com
    http:
      paths:
      - backend:
          serviceName: weddingbook-svc
          servicePort: 80