name: Build and Publish to Docker Registry
on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      REPOSITORY: asergiowiley/weddingbook
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::7})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag $REPOSITORY:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push $REPOSITORY:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image as latest
        run: docker build . --file Dockerfile --tag $REPOSITORY:latest
      - name: Push the latest Docker image as latest
        run: docker push $REPOSITORY:latest
